import { ChangeDetectionStrategy, Component, input } from '@angular/core';

export interface ApiTableRow {
  name: string;
  type: string;
  default: string;
}

/**
 * Renders the Input/Type/Default table every component doc page's `[api]`
 * slot uses. Rows are typically generated by `tools/typedoc/generate-api-docs.ts`
 * rather than hand-written — see `checkbox-doc.ts`/`radio-doc.ts`.
 */
@Component({
  selector: 'docs-api-table',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <table class="w-full border-collapse text-sm">
      <thead>
        <tr class="border-b border-border text-left text-text-muted">
          <th class="py-2 pr-4">Input</th>
          <th class="py-2 pr-4">Type</th>
          <th class="py-2">Default</th>
        </tr>
      </thead>
      <tbody>
        @for (row of rows(); track row.name) {
          <tr class="border-b border-border last:border-b-0">
            <td class="py-2 pr-4 font-mono">{{ row.name }}</td>
            <td class="py-2 pr-4 font-mono">{{ row.type }}</td>
            <td class="py-2 font-mono">{{ row.default }}</td>
          </tr>
        }
      </tbody>
    </table>
  `,
})
export class DocApiTable {
  readonly rows = input.required<ApiTableRow[]>();
}
